import type { Template, Project, HistoryItem } from "./types"

export const mockTemplates: Template[] = [
  {
    id: "1",
    name: "ビジネスプレゼン",
    description: "プロフェッショナルなビジネス向けテンプレート",
    thumbnail: "/business-presentation-template.png",
    slideCount: 5,
    slots: [
      {
        id: "s1-title",
        slideIndex: 0,
        name: "タイトル",
        type: "title",
        placeholder: "プレゼンのタイトル",
        required: true,
      },
      {
        id: "s1-subtitle",
        slideIndex: 0,
        name: "サブタイトル",
        type: "text",
        placeholder: "サブタイトルや日付",
        required: false,
      },
      { id: "s2-heading", slideIndex: 1, name: "課題", type: "title", placeholder: "解決したい課題", required: true },
      {
        id: "s2-points",
        slideIndex: 1,
        name: "課題ポイント",
        type: "list",
        placeholder: "課題を箇条書きで",
        required: true,
      },
      {
        id: "s3-heading",
        slideIndex: 2,
        name: "解決策",
        type: "title",
        placeholder: "提案するソリューション",
        required: true,
      },
      {
        id: "s3-image",
        slideIndex: 2,
        name: "イメージ",
        type: "image",
        placeholder: "製品/サービスのイメージ",
        required: false,
      },
      { id: "s3-desc", slideIndex: 2, name: "説明", type: "text", placeholder: "ソリューションの説明", required: true },
      { id: "s4-heading", slideIndex: 3, name: "効果", type: "title", placeholder: "期待される効果", required: true },
      {
        id: "s4-chart",
        slideIndex: 3,
        name: "データ",
        type: "chart",
        placeholder: "効果を示すグラフ",
        required: false,
      },
      { id: "s5-cta", slideIndex: 4, name: "CTA", type: "title", placeholder: "行動喚起", required: true },
      { id: "s5-contact", slideIndex: 4, name: "連絡先", type: "text", placeholder: "連絡先情報", required: false },
    ],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "スタートアップピッチ",
    description: "投資家向けピッチデッキ用テンプレート",
    thumbnail: "/startup-pitch-deck.jpg",
    slideCount: 6,
    slots: [
      { id: "p1-title", slideIndex: 0, name: "会社名", type: "title", placeholder: "スタートアップ名", required: true },
      {
        id: "p1-tagline",
        slideIndex: 0,
        name: "タグライン",
        type: "text",
        placeholder: "一言で表す価値",
        required: true,
      },
      { id: "p2-problem", slideIndex: 1, name: "課題", type: "text", placeholder: "解決する課題", required: true },
      {
        id: "p3-solution",
        slideIndex: 2,
        name: "ソリューション",
        type: "text",
        placeholder: "提供する解決策",
        required: true,
      },
      { id: "p4-market", slideIndex: 3, name: "市場規模", type: "chart", placeholder: "TAM/SAM/SOM", required: true },
      { id: "p5-team", slideIndex: 4, name: "チーム", type: "list", placeholder: "創業メンバー", required: true },
      { id: "p6-ask", slideIndex: 5, name: "調達額", type: "title", placeholder: "希望調達額", required: true },
    ],
    createdAt: new Date("2024-02-01"),
  },
]

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Q4事業報告",
    description: "2024年Q4の事業成果報告プレゼン",
    templateId: "1",
    templateName: "ビジネスプレゼン",
    status: "in-progress",
    slots: [
      {
        slotId: "s1-title",
        slideIndex: 0,
        name: "タイトル",
        type: "title",
        value: "2024年Q4事業報告",
        status: "approved",
        linkedStoryId: "story-1",
      },
      {
        slotId: "s1-subtitle",
        slideIndex: 0,
        name: "サブタイトル",
        type: "text",
        value: "株式会社サンプル",
        status: "filled",
      },
      {
        slotId: "s2-heading",
        slideIndex: 1,
        name: "課題",
        type: "title",
        value: "今期の課題",
        status: "filled",
        linkedStoryId: "story-2",
      },
      { slotId: "s2-points", slideIndex: 1, name: "課題ポイント", type: "list", value: "", status: "empty" },
      { slotId: "s3-heading", slideIndex: 2, name: "解決策", type: "title", value: "", status: "empty" },
      { slotId: "s3-image", slideIndex: 2, name: "イメージ", type: "image", value: "", status: "empty" },
      { slotId: "s3-desc", slideIndex: 2, name: "説明", type: "text", value: "", status: "empty" },
      { slotId: "s4-heading", slideIndex: 3, name: "効果", type: "title", value: "", status: "empty" },
      { slotId: "s4-chart", slideIndex: 3, name: "データ", type: "chart", value: "", status: "empty" },
      { slotId: "s5-cta", slideIndex: 4, name: "CTA", type: "title", value: "", status: "empty" },
      { slotId: "s5-contact", slideIndex: 4, name: "連絡先", type: "text", value: "", status: "empty" },
    ],
    story: [
      {
        id: "story-1",
        title: "導入",
        content: "2024年Q4の振り返りと成果を共有",
        slideIndices: [0],
        status: "approved",
        order: 0,
      },
      {
        id: "story-2",
        title: "課題認識",
        content: "今期直面した主要な課題",
        slideIndices: [1],
        status: "draft",
        order: 1,
      },
      {
        id: "story-3",
        title: "解決策",
        content: "課題に対するアプローチ",
        slideIndices: [2],
        status: "draft",
        order: 2,
      },
      {
        id: "story-4",
        title: "成果",
        content: "定量的な成果とKPI達成状況",
        slideIndices: [3],
        status: "draft",
        order: 3,
      },
      {
        id: "story-5",
        title: "次のアクション",
        content: "来期に向けた方針",
        slideIndices: [4],
        status: "draft",
        order: 4,
      },
    ],
    materials: [
      {
        id: "mat-1",
        name: "会社ロゴ",
        type: "image",
        content: "/generic-company-logo.png",
        tags: ["ロゴ"],
        usedInSlots: [],
      },
      {
        id: "mat-2",
        name: "成長グラフ",
        type: "chart",
        content: "growth-chart",
        tags: ["データ", "成長"],
        usedInSlots: [],
      },
    ],
    versions: [
      {
        id: "v1",
        name: "初版",
        description: "最初のドラフト",
        slots: [],
        story: [],
        createdAt: new Date("2024-03-01"),
      },
    ],
    suggestions: [
      {
        id: "sug-1",
        type: "slot-update",
        message: "「課題ポイント」を埋めると、ストーリーの流れが完成します",
        targetSlotIds: ["s2-points"],
        dismissed: false,
        createdAt: new Date(),
      },
    ],
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-05"),
  },
]

export const mockHistory: HistoryItem[] = [
  {
    id: "h1",
    projectId: "proj-1",
    type: "slot",
    action: "スロット更新",
    description: "「タイトル」を「2024年Q4事業報告」に設定",
    timestamp: new Date("2024-03-05T10:30:00"),
  },
  {
    id: "h2",
    projectId: "proj-1",
    type: "project",
    action: "プロジェクト作成",
    description: "「Q4事業報告」を作成",
    timestamp: new Date("2024-03-01T09:00:00"),
  },
]
